FuelLabs/fuel-bridge

docs/GETTING_STARTED.md

Update requirements on the documents

docs: update requirements

---

.github/workflows/release.yaml

Fix the release CI that is missing rust setup

fix: add rust setup on release ci

---

.vscode/settings.json

This PR fixes an issue with the configuration of .vscode and the sway plugin

Fix sway - codeActionsOnSave conflict

---

.changeset/popular-feet-walk.md
docker/l1-chain/Dockerfile
docker/l1-chain/Placeholder.sol
packages/fungible-token/bridge-fungible-token/src/interface/bridge.sw
packages/fungible-token/bridge-fungible-token/src/main.sw
packages/fungible-token/bridge-fungible-token/src/utils.sw
packages/solidity-contracts/contracts/messaging/FuelMessagesEnabled.sol
packages/solidity-contracts/contracts/messaging/FuelMessagesEnabledUpgradeable.sol
packages/solidity-contracts/contracts/messaging/gateway/FuelBridgeBase.sol
packages/solidity-contracts/contracts/messaging/gateway/FuelERC20Gateway.sol
packages/solidity-contracts/contracts/messaging/gateway/FuelERC721Gateway.sol
packages/solidity-contracts/contracts/messaging/gateway/v2/FuelBridgeBaseV2.sol
packages/solidity-contracts/contracts/messaging/gateway/v2/FuelERC20GatewayV2.sol
packages/solidity-contracts/contracts/messaging/gateway/v2/FuelERC721GatewayV2.sol
packages/solidity-contracts/protocol/harness.ts
packages/solidity-contracts/test/erc20GatewayV2.test.ts
packages/solidity-contracts/test/erc721GatewayV2.test.ts
packages/solidity-contracts/test/utils/impersonateAccount.ts
packages/test-utils/src/utils/fuels/getOrDeployFuelTokenContract.ts

This PR adds a handshake protocol that ensures no funds are lost when depositing in the canonical bridge.

Bridge handshake protocol

---

.changeset/shy-grapes-turn.md
.github/actions/setup-rust/action.yml
Cargo.lock
Cargo.toml
docker/fuel-core/Dockerfile
packages/esbuild-bin-loader/package.json
packages/fungible-token/README.md
packages/fungible-token/test-deposit-recipient-contract/fuel-toolchain.toml
packages/integration-tests/package.json
packages/test-utils/package.json
packages/test-utils/src/utils/fuels/relayCommonMessage.ts
pnpm-lock.yaml

```
fuel-core - 0.20.7
fuels - 0.63.0
rust - 1.73.0
forc - 0.46.0
```

feat: update to beta-4

---

.changeset/tame-seals-bake.md
packages/solidity-contracts/contracts/fuelchain/FuelMessagePortal.sol
packages/solidity-contracts/contracts/lib/CommonPredicates.sol
packages/solidity-contracts/contracts/messaging/gateway/FuelERC20Gateway.sol

Closes #111 
Some automatic prettier reformatting seems to have taken place

Extract CommonPredicates lib into its own file

---

.changeset/four-lizards-tell.md
packages/solidity-contracts/contracts/fuelchain/FuelMessagePortal/IFuelMessagePortal.sol

Add nonce to FTI interface

---

.changeset/metal-walls-doubt.md
packages/solidity-contracts/contracts/fuelchain/FuelMessagePortal/v3/FuelMessagePortalV3.sol
packages/solidity-contracts/test/messagesIncomingV3.test.ts
packages/solidity-contracts/test/utils/createRandomWalletWithFunds.ts
packages/solidity-contracts/test/utils/index.ts

Improve permission granularity for message blacklisting

---

.changeset/twenty-days-reflect.md
package.json
packages/integration-tests/package.json
pnpm-lock.yaml

(ci): Remove pnpm audit conflicting deps

---

.changeset/afraid-months-lay.md
packages/integration-tests/tests/transfer_eth.ts
packages/test-utils/src/utils/ethers/waitForBlockCommit.ts
packages/test-utils/src/utils/fuels/index.ts
packages/test-utils/src/utils/fuels/waitForBlock.ts

Closes #224 
Also fixes some detected flakiness around the e2e test `transfer_eth`

test: increase integration test coverage

---

.changeset/gentle-clocks-burn.md
packages/solidity-contracts/.openzeppelin/sepolia.json
packages/solidity-contracts/deploy/devnet/012.configure_l2_issuer.ts
packages/solidity-contracts/deployments/devnet/.migrations.json
packages/solidity-contracts/deployments/devnet/FuelERC20GatewayV4.json
packages/solidity-contracts/deployments/devnet/FuelL2BridgeId.json

chore: deploy new token bridge for devnet

---

.changeset/healthy-apricots-divide.md
packages/solidity-contracts/contracts/messaging/gateway/FuelERC20Gateway/FuelERC20GatewayV4.sol

- closes https://github.com/FuelLabs/fuel-bridge/issues/303

fix comment in FuelERC20GatewayV4

---

.changeset/late-pears-matter.md
packages/solidity-contracts/contracts/fuelchain/FuelChainState.sol
packages/solidity-contracts/test/fuelChainState.ts

- closes https://github.com/FuelLabs/fuel-bridge/issues/305

add zero address check for time to finalise

---

docs/ARCHITECTURE.md

- closes https://github.com/FuelLabs/fuel-bridge/issues/269

Upgrades decimal conversion documentation

---

.changeset/smooth-carrots-visit.md
packages/integration-tests/tests/bridge_erc20.ts
packages/integration-tests/tests/bridge_mainnet_tokens.ts
packages/solidity-contracts/contracts/messaging/gateway/FuelERC20Gateway/FuelERC20GatewayV4.sol
packages/solidity-contracts/test/behaviors/erc20GatewayV4.behavior.test.ts
packages/solidity-contracts/test/fuelChainState.ts

- closes https://github.com/FuelLabs/fuel-bridge/issues/309

Disable/Enable rate limit for erc20 tokens 

---

.changeset/tough-bugs-sip.md
packages/integration-tests/tests/transfer_eth.ts
packages/solidity-contracts/contracts/fuelchain/FuelMessagePortal/v3/FuelMessagePortalV3.sol

update naming convention for immutable var

---

.changeset/giant-forks-rush.md
packages/integration-tests/tests/transfer_eth.ts
packages/solidity-contracts/contracts/fuelchain/FuelMessagePortal/v3/FuelMessagePortalV3.sol
packages/solidity-contracts/test/behaviors/erc20GatewayV4.behavior.test.ts
packages/solidity-contracts/test/messagesIncomingV3.test.ts

feat: add rate limit status check on FuelMessagePortalV3

---

.changeset/nasty-mayflies-explode.md
Forc.lock
fuel-toolchain.toml

chore: upgrade forc to 0.64.0

---

docs/ARCHITECTURE.md

doc: add detailed docs on resetting rate limit

---

.changeset/hot-wombats-confess.md

chore: modify changeset to target v1.0.0

---

.changeset/chatty-panthers-cry.md
.changeset/clever-ghosts-reply.md
.changeset/few-rivers-fix.md
.changeset/giant-forks-rush.md
.changeset/gold-zebras-hug.md
.changeset/green-carrots-rule.md
.changeset/healthy-apricots-divide.md
.changeset/hot-wombats-confess.md
.changeset/late-pears-matter.md
.changeset/nasty-mayflies-explode.md
.changeset/plenty-rice-laugh.md
.changeset/real-pots-clean.md
.changeset/smooth-carrots-visit.md
.changeset/sweet-chicken-dress.md
.changeset/tasty-mice-mix.md
.changeset/tough-bugs-sip.md
.changeset/violet-cups-retire.md
packages/fungible-token/CHANGELOG.md
packages/fungible-token/package.json
packages/message-predicates/CHANGELOG.md
packages/message-predicates/package.json
packages/solidity-contracts/CHANGELOG.md
packages/solidity-contracts/package.json
packages/test-utils/CHANGELOG.md
packages/test-utils/package.json

This reverts commit 9229a0d6cdfc4c7feaf35334f1565f574696d598.

Revert "ci(changesets): versioning packages (#285)"

---

.changeset/violet-rice-explain.md
.github/workflows/manual-verify-upgrade.yml
packages/solidity-contracts/.openzeppelin/sepolia.json
packages/solidity-contracts/deployments/upgradeTest/FuelChainState.json
packages/solidity-contracts/deployments/upgradeTest/FuelERC20GatewayV4.json
packages/solidity-contracts/deployments/upgradeTest/FuelMessagePortalV3.json

- update manual verify upgrade payload file path in ci

fix: manual verify upgrade ci

---

.changeset/dirty-hornets-watch.md
.github/workflows/manual-query-grant-role-event.yml
packages/solidity-contracts/scripts/hardhat/eventFilter.ts

- adds absolute path in ci for uploading the event logs json file

fix: grant role event log ci

---

.github/workflows/pr.yml
package.json
pnpm-lock.yaml

- closes https://github.com/FuelLabs/fuel-bridge/issues/371

fix: CI issues

---

.changeset/metal-chefs-happen.md
packages/solidity-contracts/package.json
pnpm-lock.yaml

fix: docker build error

---

packages/solidity-contracts/.openzeppelin/sepolia.json

chore: restore OZ sepolia artifacts
